### ISSUE TITLE
ValueError: Descending test id on line ...

### ISSUE THREAD

**Issue by ForbiddenEra** [nodejs/tap2junit#50]
Trying to use this to convert the `tap` output from the built-in test runner to `junit` for CI/CD use.

```shell
# ~/.local/bin/tap2junit -i tests/report.txt -o tests/report.xml
Traceback (most recent call last):
  File "~/.local/bin/tap2junit", line 8, in <module>
    sys.exit(main())
  File "~/.local/pipx/venvs/tap2junit/lib/python3.8/site-packages/tap2junit/__main__.py", line 94, in main
    convert(
  File "~/.local/pipx/venvs/tap2junit/lib/python3.8/site-packages/tap2junit/__main__.py", line 68, in convert
    result = parse(name or input_file, data, package)
  File "~/.local/pipx/venvs/tap2junit/lib/python3.8/site-packages/tap2junit/__main__.py", line 58, in parse
    tap_parser.parse(data)
  File "~/.local/pipx/venvs/tap2junit/lib/python3.8/site-packages/tap2junit/tap13.py", line 238, in parse
    self._parse(io.StringIO(source))
  File "~/.local/pipx/venvs/tap2junit/lib/python3.8/site-packages/tap2junit/tap13.py", line 193, in _parse
    raise ValueError("Descending test id on line: %r" % line)
ValueError: Descending test id on line: 'ok 1 - fileSize checks'
```

report.txt (as outputted from `node --test-reporter=tap --test-reporter-destination=report.txt tests/run-tests.js`)
```yaml
TAP version 13
# Subtest: System Configuration Required Tests
ok 1 - System Configuration Required Tests # TODO System Configuration Required Tests
  ---
  duration_ms: 3.723
  ...
# Subtest: System Configuration Optional Tests
    # Subtest: System Configuration Optional Tests
    ok 1 - System Configuration Optional Tests
      ---
      duration_ms: 3.2683
      ...
    1..1
ok 2 - System Configuration Optional Tests
  ---
  duration_ms: 4.5664
  ...
# Subtest: Main Validation Tests
    # Subtest: fileSize checks
        # Subtest: fileSize is too small
        ok 1 - fileSize is too small
          ---
          duration_ms: 20.9785
          ...
        # Subtest: fileSize is too large
        ok 2 - fileSize is too large
          ---
          duration_ms: 27.1384
          ...
        1..2
    ok 1 - fileSize checks
      ---
      duration_ms: 51.8895
      ...
    1..1
ok 3 - Main Validation Tests
  ---
  duration_ms: 53.4117
  ...
1..3
# tests 3
# pass 2
# fail 0
# cancelled 0
# skipped 0
# todo 1
# duration_ms 81.1599
```

Not entirely sure why this is happening but if I had to guess it's nesting depth/recursion related..?

**Comment by cclauss** [comment]
@MoLow Any ideas?

@ForbiddenEra We made a [new release](https://github.com/nodejs/tap2junit/releases) this morning.  Can you try `pip install tap2junit==0.1.5` vs. `pip install tap2junit==0.1.6` and see if you get the same or different results/

**Comment by MoLow** [comment]
this seems to reproduce on `0.1.6`.
validation of test numbering seems to ignore nesting.
@ForbiddenEra you can take a look at https://www.npmjs.com/package/@reporters/junit

**Comment by ForbiddenEra** [comment]
> this seems to reproduce on `0.1.6`. validation of test numbering seems to ignore nesting. @ForbiddenEra you can take a look at https://www.npmjs.com/package/@reporters/junit

Oo, will take a peek - nice to see an alternative, I was tempted to whip up my own since the XML doesn't look too complex but no sense in re-inventing any wheels, I'll take a peek at that; fortunately I can have my tests still run properly and specify a reporter on the command line without using `--test` or using `run()` (https://github.com/nodejs/node/issues/47314 describes in more detail what/why etc and it seems like commits are coming to improve this for my case)

I should also mention that the XML that I did get out of it when removing nesting wasn't the greatest either; it didn't pick up any 'filenames' and split any of my test comments/descriptions up that had a `/` character in them:

```xml
<?xml version="1.0" encoding="utf-8"?>
<testsuites disabled="0" errors="0" failures="0" tests="17" time="4.4751723">
	<testsuite disabled="0" errors="0" failures="0" name="tests/report" skipped="2" tests="17" time="4.4751723" hostname="ForbiddenEra">
		<testcase name="- System Configuration Required Tests " time="0.003377">
			<skipped type="skipped" message="System Configuration Required Tests"/>
		</testcase>
		<testcase name="- System Configuration Optional Tests" time="0.001361"/>
		<testcase name="- System Configuration Optional Tests" time="0.002587"/>
		<testcase name="- fileSize is too small" time="0.023804"/>
		<testcase name="- fileSize is too large" time="0.033457"/>
		<testcase name="- fileType is invalid" time="0.096726"/>
		<testcase name="- fileType mismatch" time="0.003848"/>
		<testcase name="- jpeg vs jpeg handling" time="0.831943"/>
		<testcase name="- image dimensions too small" time="0.003943"/>
		<testcase name="- image dimensions too large, resize (x&gt;y)" time="0.444136"/>
		<testcase name="- image dimensions too large, resize (y&gt;x)" time="0.421050"/>
		<testcase name="metadata stripping" time="0.368525" classname="- image exif"/>
		<testcase name="- Main Validation Tests" time="2.231721"/>
		<testcase name="- VirusTotal FAIL test - EICAR-STANDARD-ANTIVIRUS-TEST-FILE" time="0.001433"/>
		<testcase name="1000x750-JPG.jpg" time="0.001964" classname="- VirusTotal PASS test - ..images"/>
		<testcase name="- VirusTotal Tests" time="0.004483"/>
		<testcase name="- PDF-Related Validation Tests " time="0.000814">
			<skipped type="skipped" message="verify PDF was exported as JPG"/>
		</testcase>
	</testsuite>
</testsuites>
```

Which results in `meh` output on Gitlab, which is ultimately my goal:

![image](https://user-images.githubusercontent.com/7980490/229330112-a7115f10-289d-4f46-99f9-7bd7d910ed89.png)

Any comments on this? None of my tests are actually named with a `- ` at the beginning, it's simply picking that up from `node:test`'s output.

I never tried `0.1.5` as I had only started testing with it that same day, I can give that a shot too if it might be worth it, though I worry that even if it handles nesting appropriately that this "secondary" issue may still be present.

I'll definitely try the mentioned reporter and if I find time I may also try `0.1.5` but ultimately if the reporter works for me than I'm happy and might not have time otherwise.

**Comment by ForbiddenEra** [comment]
Tried the `@reporters/junit` quickly and the result seems better:

(still not showing any filenames but a marked improvement)
```xml
<?xml version="1.0" encoding="utf-8"?>
<testsuites>
        <testcase name="System Configuration Required Tests" time="0.002037" classname="test">
                <skipped type="todo" message="System Configuration Required Tests/Test 1"/>
        <testsuite name="System Configuration Optional Tests" time="0.000468" disabled="0" errors="0" tests="1" failures="0" skipped="0" hostname="ForbiddenEra">
                <testcase name="System Configuration Optional Tests/Test 1" time="0.000210" classname="test"/>
        </testsuite>
        <testsuite name="Main Validation Tests" time="3.578587" disabled="0" errors="0" tests="3" failures="0" skipped="0" hostname="ForbiddenEra">
                <testsuite name="fileSize checks" time="0.047023" disabled="0" errors="0" tests="2" failures="0" skipped="0" hostname="ForbiddenEra">
                        <testcase name="fileSize is too small" time="0.021639" classname="test"/>
                        <testcase name="fileSize is too large" time="0.022921" classname="test"/>
                </testsuite>
                <testsuite name="fileType checks" time="2.306216" disabled="0" errors="0" tests="3" failures="0" skipped="0" hostname="ForbiddenEra">
                        <testcase name="fileType is invalid" time="1.463701" classname="test"/>
                        <testcase name="fileType mismatch" time="0.001962" classname="test"/>
                        <testcase name="jpeg vs jpeg handling" time="0.838738" classname="test"/>
                </testsuite>
                <testsuite name="image metadata, dimensions and resize checks" time="1.224442" disabled="0" errors="0" tests="4" failures="0" skipped="0" hostname="ForbiddenEra">
                        <testcase name="image dimensions too small" time="0.004724" classname="test"/>
                        <testcase name="image dimensions too large, resize (x>y)" time="0.434010" classname="test"/>
                        <testcase name="image dimensions too large, resize (y>x)" time="0.399356" classname="test"/>
                        <testcase name="image exif/metadata stripping" time="0.384762" classname="test"/>
                </testsuite>
        </testsuite>
        <testsuite name="VirusTotal Tests" time="0.002964" disabled="0" errors="0" tests="2" failures="0" skipped="0" hostname="ForbiddenEra">
                <testcase name="VirusTotal FAIL test - EICAR-STANDARD-ANTIVIRUS-TEST-FILE" time="0.000588" classname="test"/>
                <testcase name="VirusTotal PASS test - ./images/1000x750-JPG.jpg" time="0.001650" classname="test"/>
        </testsuite>
        <testcase name="PDF-Related Validation Tests" time="0.000352" classname="test">
                <skipped type="todo" message="verify PDF was exported as JPG"/>
        </testcase>
        </testcase>
</testsuites>
```

I also tried installing `0.1.5` but can't (easily) 100% confirm that it overrode `0.1.6` as it doesn't provide a `--version` or similar option, though it installed fine and got the same result for descending values.

**Comment by MoLow** [comment]
@ForbiddenEra can you please open an issue at https://github.com/MoLow/reporters/tree/main describing what the desired output would be and what node version you are using?

**Comment by ForbiddenEra** [comment]
> @ForbiddenEra can you please open an issue at https://github.com/MoLow/reporters/tree/main describing what the desired output would be and what node version you are using?

No problem; I did ask if you would prefer that and will do..
